extends Node

enum CardType {
	NULL,
	ROCK,
	PAPER,
	SCISSORS,
	GUN,
	MIMIC,
	GOD
}

const CardTypeName : Dictionary = {
	CardType.ROCK: "Rock",
	CardType.PAPER: "Paper",
	CardType.SCISSORS: "Scissor",
	CardType.GUN: "Gun",
	CardType.MIMIC: "Mimic",
	CardType.GOD: "God"
}

const BasicIds : Dictionary = {
	CardType.ROCK: 1,
	CardType.PAPER: 2,
	CardType.SCISSORS: 3,
	CardType.GUN: 4,
	CardType.MIMIC: 5,
	CardType.GOD: 42
}

const NUT_IDS : Array = [
	58,
	59,
	60,
	61,
	62,
	63,
	64,
	65
];

const BasicNames : Dictionary = {
	CardType.ROCK: "a Pebble",
	CardType.PAPER: "a Scribble Paper",
	CardType.SCISSORS: "Paper Scissors",
	CardType.MIMIC: "a Lesser Mimic",
	CardType.GUN: "The Gun",
	CardType.GOD: "The Zescanor"
}

const TranslateCardType : Dictionary = {
	"rock": CardType.ROCK,
	"paper": CardType.PAPER,
	"scissor": CardType.SCISSORS,
	"gun": CardType.GUN,
	"mimic": CardType.MIMIC,
	"god": CardType.GOD
}

enum Zone {
	DECK,
	HAND,
	FIELD,
	GRAVE
}

enum Keyword {
	NULL,
	BURIED,
	CARROT_EATER,
	CELEBRATE,
	CHAMELEON,
	CHAMPION,
	COOTIES,
	COPYCAT,
	CURSED,
	DEVOUR,
	DIGITAL,
	DIVINE,
	ELECTROCUTE,
	EMP,
	EXTRA_SALTY,
	GREED,
	HIGH_GROUND,
	HIGH_NUT,
	HORSE_GEAR,
	HYDRA,
	INFLUENCER,
	MULTI_SPY,
	MUSHY,
	NOVEMBER,
	NUT,
	NUT_COLLECTOR,
	NUT_STEALER,
	OCEAN,
	OCEAN_DWELLER,
	PAIR,
	PAIR_BREAKER,
	PICK_UP,
	RAINBOW,
	RELOAD,
	RUST,
	SALTY,
	SCAMMER,
	SECRETS,
	SHARED_NUT,
	SILVER,
	SOUL_HUNTER,
	SPY,
	TIDAL,
	TIDAL_WAVE,
	TIME_STOP,
	UNDEAD,
	VAMPIRE,
	VERY_NUTTY,
	WRAPPED
}

func get_hydra_keywords() -> Array:
	return [
		Keyword.BURIED,
		Keyword.CARROT_EATER,
		Keyword.CELEBRATE,
		Keyword.CHAMELEON,
		Keyword.CHAMPION,
		Keyword.COOTIES,
		Keyword.COPYCAT,
		Keyword.CURSED,
		Keyword.DEVOUR,
		Keyword.DIVINE,
		Keyword.ELECTROCUTE,
		Keyword.EMP,
		Keyword.EXTRA_SALTY,
		Keyword.GREED,
		Keyword.HIGH_GROUND,
		Keyword.HIGH_NUT,
		Keyword.INFLUENCER,
		Keyword.MULTI_SPY,
		Keyword.NOVEMBER,
		Keyword.NUT,
		Keyword.NUT_COLLECTOR,
		Keyword.NUT_STEALER,
		Keyword.OCEAN,
		Keyword.PAIR,
		Keyword.PAIR_BREAKER,
		Keyword.RAINBOW,
		Keyword.RELOAD,
		Keyword.RUST,
		Keyword.SALTY,
		Keyword.SHARED_NUT,
		Keyword.SILVER,
		Keyword.SOUL_HUNTER,
		Keyword.SPY,
		Keyword.TIDAL_WAVE,
		Keyword.TIME_STOP,
		Keyword.UNDEAD,
		Keyword.VAMPIRE,
		Keyword.VERY_NUTTY,
		Keyword.WRAPPED
	];

const KeywordNames : Dictionary = {
	Keyword.BURIED : "Buried",
	Keyword.CARROT_EATER : "Carrot-eater",
	Keyword.CELEBRATE : "Celebrate",
	Keyword.CHAMELEON : "Chameleon",
	Keyword.CHAMPION : "Champion",
	Keyword.COOTIES : "Cooties",
	Keyword.COPYCAT : "Copycat",
	Keyword.CURSED : "Cursed",
	Keyword.DEVOUR : "Devour",
	Keyword.DIGITAL : "Digital",
	Keyword.DIVINE : "Divine",
	Keyword.ELECTROCUTE : "Electrocute",
	Keyword.EMP : "EMP",
	Keyword.EXTRA_SALTY : "Extra-salty",
	Keyword.GREED : "Greed",
	Keyword.HIGH_GROUND : "High-ground",
	Keyword.HIGH_NUT : "High-nut",
	Keyword.HORSE_GEAR : "Horse-gear",
	Keyword.HYDRA : "Hydra",
	Keyword.INFLUENCER : "Influencer",
	Keyword.MULTI_SPY : "Multi-spy",
	Keyword.MUSHY : "Mushy",
	Keyword.NOVEMBER : "November",
	Keyword.NUT : "Nut",
	Keyword.NUT_COLLECTOR : "Nut Collector",
	Keyword.NUT_STEALER : "Nut Stealer",
	Keyword.OCEAN : "Ocean",
	Keyword.OCEAN_DWELLER : "Ocean Dweller",
	Keyword.PAIR : "Pair",
	Keyword.PAIR_BREAKER : "Pair-breaker",
	Keyword.PICK_UP : "Pick-up",
	Keyword.RAINBOW : "Rainbow",
	Keyword.RELOAD : "Reload",
	Keyword.RUST : "Rust",
	Keyword.SALTY : "Salty",
	Keyword.SCAMMER : "Scammer",
	Keyword.SECRETS : "Secrets",
	Keyword.SHARED_NUT : "Shared Nut",
	Keyword.SILVER : "Silver",
	Keyword.SOUL_HUNTER : "Soul Hunter",
	Keyword.SPY : "Spy",
	Keyword.TIDAL : "Tidal",
	Keyword.TIDAL_WAVE : "Tidal Wave",
	Keyword.TIME_STOP : "Time-stop",
	Keyword.UNDEAD : "Undead",
	Keyword.VAMPIRE : "Vampire",
	Keyword.VERY_NUTTY : "Very Nutty",
	Keyword.WRAPPED : "Wrapped"
}

const TranslateKeyword : Dictionary = {
	"buried" : Keyword.BURIED,
	"carrot-eater" : Keyword.CARROT_EATER,
	"celebrate" : Keyword.CELEBRATE,
	"chameleon" : Keyword.CHAMELEON,
	"champion" : Keyword.CHAMPION,
	"cooties" : Keyword.COOTIES,
	"copycat" : Keyword.COPYCAT,
	"cursed" : Keyword.CURSED,
	"devour" : Keyword.DEVOUR,
	"digital" : Keyword.DIGITAL,
	"divine" : Keyword.DIVINE,
	"electrocute" : Keyword.ELECTROCUTE,
	"emp" : Keyword.EMP,
	"extra-salty" : Keyword.EXTRA_SALTY,
	"greed" : Keyword.GREED,
	"high-ground" : Keyword.HIGH_GROUND,
	"high-nut" : Keyword.HIGH_NUT,
	"horse-gear" : Keyword.HORSE_GEAR,
	"hydra" : Keyword.HYDRA,
	"influencer" : Keyword.INFLUENCER,
	"multi-spy" : Keyword.MULTI_SPY,
	"mushy" : Keyword.MUSHY,
	"november" : Keyword.NOVEMBER,
	"nut" : Keyword.NUT,
	"nut-collector" : Keyword.NUT_COLLECTOR,
	"nut-stealer" : Keyword.NUT_STEALER,
	"ocean" : Keyword.OCEAN,
	"ocean-dweller" : Keyword.OCEAN_DWELLER,
	"pair" : Keyword.PAIR,
	"pair-breaker" : Keyword.PAIR_BREAKER,
	"pick-up" : Keyword.PICK_UP,
	"rainbow" : Keyword.RAINBOW,
	"reload" : Keyword.RELOAD,
	"rust" : Keyword.RUST,
	"salty" : Keyword.SALTY,
	"scammer" : Keyword.SCAMMER,
	"secrets" : Keyword.SECRETS,
	"shared-nut" : Keyword.SHARED_NUT,
	"silver" : Keyword.SILVER,
	"soul-hunter" : Keyword.SOUL_HUNTER,
	"spy" : Keyword.SPY,
	"tidal" : Keyword.TIDAL,
	"tidal-wave" : Keyword.TIDAL_WAVE,
	"time-stop" : Keyword.TIME_STOP,
	"undead" : Keyword.UNDEAD,
	"vampire" : Keyword.VAMPIRE,
	"very-nutty" : Keyword.VERY_NUTTY,
	"wrapped" : Keyword.WRAPPED
}

const TranslateKeywordBack: Dictionary = {
	Keyword.BURIED : "buried",
	Keyword.CARROT_EATER : "carrot-eater",
	Keyword.CELEBRATE : "celebrate",
	Keyword.CHAMELEON : "chameleon",
	Keyword.CHAMPION : "champion",
	Keyword.COOTIES : "cooties",
	Keyword.COPYCAT : "copycat",
	Keyword.CURSED : "cursed",
	Keyword.DEVOUR : "devour",
	Keyword.DIGITAL : "digital",
	Keyword.DIVINE : "divine",
	Keyword.ELECTROCUTE : "electrocute",
	Keyword.EMP : "emp",
	Keyword.EXTRA_SALTY : "extra-salty",
	Keyword.GREED : "greed",
	Keyword.HIGH_GROUND : "high-ground",
	Keyword.HIGH_NUT : "high-nut",
	Keyword.HORSE_GEAR : "horse-gear",
	Keyword.HYDRA : "hydra",
	Keyword.INFLUENCER : "influencer",
	Keyword.MULTI_SPY : "multi-spy",
	Keyword.MUSHY : "mushy",
	Keyword.NOVEMBER : "november",
	Keyword.NUT : "nut",
	Keyword.NUT_COLLECTOR : "nut-collector",
	Keyword.NUT_STEALER : "nut-stealer",
	Keyword.OCEAN : "ocean",
	Keyword.OCEAN_DWELLER : "ocean-dweller",
	Keyword.PAIR : "pair",
	Keyword.PAIR_BREAKER : "pair-breaker",
	Keyword.PICK_UP : "pick-up",
	Keyword.RAINBOW : "rainbow",
	Keyword.RELOAD : "reload",
	Keyword.RUST : "rust",
	Keyword.SALTY : "salty",
	Keyword.SCAMMER : "scammer",
	Keyword.SECRETS : "secrets",
	Keyword.SHARED_NUT : "shared-nut",
	Keyword.SILVER : "silver",
	Keyword.SOUL_HUNTER : "soul-hunter",
	Keyword.SPY : "spy",
	Keyword.TIDAL : "tidal",
	Keyword.TIDAL_WAVE : "tidal-wave",
	Keyword.TIME_STOP : "time-stop",
	Keyword.UNDEAD : "undead",
	Keyword.VAMPIRE : "vampire",
	Keyword.VERY_NUTTY : "very-nutty",
	Keyword.WRAPPED : "wrapped"
}

var KeywordHints : Dictionary = {
	Keyword.BURIED : "Played face-down.",
	Keyword.CARROT_EATER : "Eats a random keyword from opponent.",
	Keyword.CELEBRATE : "Discard your hand, then draw 1.",
	Keyword.CHAMELEON : "Whenever opponent gets a card, changes color.",
	Keyword.CHAMPION : "Games with this card give double points.",
	Keyword.COOTIES : "Defeats any card without an effect.",
	Keyword.COPYCAT : "Copies opponent's card type.",
	Keyword.CURSED : "Cannot be replaced or destroyed.",
	Keyword.DEVOUR : "Eats the first card opponent plays.",
	Keyword.DIGITAL : "Counterspell from hand. [i](Replaces the card you played.)[/i]",
	Keyword.DIVINE : "Defeats any undead.",
	Keyword.ELECTROCUTE : "Defeats any wet card.",
	Keyword.EMP : "Negates digital.",
	Keyword.EXTRA_SALTY : "If loses, lose all your points.",
	Keyword.GREED : "If loses, draw 2.",
	Keyword.HIGH_GROUND : "Automatically defeats any face-down card.",
	Keyword.HIGH_NUT : "Nuts on any face-down card.",
	Keyword.HORSE_GEAR : "Starts in your opening hand.",
	Keyword.HYDRA : "Gains 3 random keywords.",
	Keyword.INFLUENCER : "Opponent's top card becomes SAME_BASIC.",
	Keyword.MULTI_SPY : "Fights up to 3 random cards in opponent's hand.",
	Keyword.MUSHY : "Loses to any rock.",
	Keyword.NOVEMBER : "Defeats any nut.",
	Keyword.NUT : "Point for every turn since your last nut.",
	Keyword.NUT_COLLECTOR : "Shuffle 3 nuts into your deck.",
	Keyword.NUT_STEALER : "If opponent would nut, you nut twice instead.",
	Keyword.OCEAN : "Scissors gain rust rust, papers gain mushy.",
	Keyword.OCEAN_DWELLER : "After every 2 turns in hand, gain a point. [i](Also triggers if becomes wet.)[/i]",
	Keyword.PAIR : "Wins in a tie.",
	Keyword.PAIR_BREAKER : "Defeats any card with pair.",
	Keyword.PICK_UP : "End of turn, discard this card from your hand.",
	Keyword.RAINBOW : "Each card in opponent's hand becomes a random card of same type.",
	Keyword.RELOAD : "Shuffle a random gun into your deck.",
	Keyword.RUST : "Defeats any gun.",
	Keyword.SALTY : "If loses, lose a point.",
	Keyword.SCAMMER : "You will get 100 points.",
	Keyword.SECRETS : "Loses to spies and gives them 3 points.",
	Keyword.SHARED_NUT : "Both players nut.",
	Keyword.SILVER : "Defeats any werewolf.",
	Keyword.SOUL_HUNTER : "You get the cards this defeats at the start of next game.",
	Keyword.SPY : "Fights a random card in opponent's hand.",
	Keyword.TIDAL : "If becomes wet, gains tidal wave.",
	Keyword.TIDAL_WAVE : "Summons a zunami.",
	Keyword.TIME_STOP : "Extends your turn.",
	Keyword.UNDEAD : "Takes %s SAME_TYPES from your grave and turns into a gun." % [System.Rules.UNDEAD_LIMIT],
	Keyword.VAMPIRE : "If wins, drains the points from opponent.",
	Keyword.VERY_NUTTY : "Doubles your next nut.",
	Keyword.WRAPPED : "Next card you play, gains buried."
}

static func translate_keywords(source : Array) -> Array:
	var translated : Array;
	for keyword in source:
		translated.append(TranslateKeyword[keyword]);
	return translated;

static func translate_keywords_back(source : Array) -> Array:
	var translated : Array;
	for keyword in source:
		translated.append(TranslateKeywordBack[keyword]);
	return translated;
